### ISSUE TITLE
Improve CodSpeed reporting

### ISSUE THREAD

**Issue by adriencaccia** [nautechsystems/nautilus_trader#2029]
Hey @cjdsellers, I am a founder @CodSpeedHQ, super glad to see that you that you started integrating CodSpeed 🥳 

In your integration, I noticed that you are running CodSpeed twice, because the job is in a matrix: https://github.com/nautechsystems/nautilus_trader/blob/develop/.github/workflows/build.yml#L167-L171

At the moment, we only support having a single run per commit, so to have the best results possible, I would recommend inly running this step when you are at the latest python version, using something like the following (the syntax might be a bit off):

```yaml
      - name: Run benchmarks (Linux)
        if: ${{ matrix.python-version }} == "3.12"
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: make test-performance
```
